### ISSUE TITLE
Keyboard shortcuts for system commands

### ISSUE THREAD

**Issue by mobitar** [standardnotes/electron#2]
Ctrl + c/v for copy paste, etc

**Comment by martynchamberlin** [comment]
Yes, the ability to copy and paste would be amazing. I'm having all kinds of password issues for lack of this. :)

**Comment by mobitar** [comment]
Ya, I know :/ Weird that Electron doesn't provide this out of the box. Planning on releasing update some time this weekend.

**Comment by martynchamberlin** [comment]
I'm also noticing a lack of continuity between the mac app and the website. Should the feature of logging into the same account on both work? I also noticed that the password reset didn't seem to trigger an email.

**Comment by mobitar** [comment]
Yes it should. They should be the exact same service. What discrepancies are you seeing?

Actually, local encryption used to be optional, but now it's default, so there will be no password reset option. (You can't have real end-to-end encryption and a password reset). So I'll need to make changes to communicate that.

**Comment by martynchamberlin** [comment]
Probably what happened was that I typed the auto-generated password from Secrets incorrectly on the mac app, then pasted the correct version into the web app, but since these didn't match, no dice, and since password reset wasn't an option, that account was toast.

I just now signed up with a new email address and everything works now. Yay. 

The tl;dr here is that we need to get the clipboard working. And you're right that literally zero key combinations work. Things like closing the window (CMD + W on my Mac). Hopefully there's just a config bool variable you can flip to get that working, or something...

**Comment by mobitar** [comment]
Awesome, hang in there. Getting this up is definitely highest on my list. I'm just tweaking the sync algo now, and after that, will tackle this one.

**Comment by martynchamberlin** [comment]
Are socket.io (or similar) in the future, for realtime (ish) note updating? That's one thing I like about Simplenote that would be great to see here.

**Comment by mobitar** [comment]
It's tempting for sure, but it's a compromise between maintainability and feature-richness. Sockets are hi-tech, which means more hours spent coding, maintaining, securing, fixing, etc. The number one goal with this project is to last longer than any other notes app. Making these compromises improves that outcome. 

But I won't rule it out. Just for now, it's definitely not a priority. The sync algorithm will pull in any changes every time you type a character in a note anyway, so you should be up to date most of the time. There'll also be a refresh button in the lower right corner for manual control. This will be released tonight.

**Comment by martynchamberlin** [comment]
@mobitar Makes sense! 

For mass adoption I think web sockets (or some equivalent fast-sync method... sounds like the algorithm you're doing is somehow achieving a similar result?) are considered important to a lot of people. I wonder if there's a way to have it with graceful fallback so that if the fast sync technology breaks, the slower sync can step in and still function. That would give the best of both worlds—long lasting software but still every bit as good of a UX.

**Comment by mobitar** [comment]
Yup, definitely worth considering. I think I'd want to figure out a way to install those kinds of services as "modules" and not part of the base code. This way, we can at least have a minimum that is always maintained, and the harder stuff can be optional.

**Comment by mobitar** [comment]
New sync system is live. Check it out and let me know what you think. Should hopefully be a smooth transition.

**Comment by martynchamberlin** [comment]
Yep. Nicely done!

**Comment by mobitar** [comment]
Fixed. New versions available here: https://github.com/standardnotes/electron/releases
